/**
 * Provider abstraction for product visual generation (DOC-105 / DOC-106).
 *
 * A "product visual" is a concept image for product presentation. It is NEVER
 * implementation source code. Two kinds exist:
 *   - product_showcase: a Product Hunt style launch-gallery image.
 *   - product_icon: an Open-Launch style app icon.
 *
 * The default provider is `local_svg` (deterministic, offline, always the
 * fallback). AI providers (imagen / openai_images) are opt-in via env vars and
 * are only reached when explicitly enabled. This file is pure — it defines
 * types and prompt builders only and must not perform any network I/O.
 */

export type VisualProviderId = "local_svg" | "imagen" | "openai_images" | "nano_banana";

export type ProductVisualKind = "product_showcase" | "product_icon";

export type ProductVisualImageMimeType = "image/png" | "image/webp" | "image/svg+xml";

export type ProductVisualGenerateArgs = {
  kind: ProductVisualKind;
  title: string;
  oneLiner: string;
  category: string;
  /** Fully-rendered prompt text (from buildPromptForKind). */
  prompt: string;
  /** Absolute path where the provider should write the generated bytes. */
  outputPath: string;
};

export type ProductVisualGenerateResult = {
  path: string;
  mimeType: ProductVisualImageMimeType;
  model?: string;
  providerRequestId?: string;
};

export type ProductVisualImageProvider = {
  id: VisualProviderId;
  generate(args: ProductVisualGenerateArgs): Promise<ProductVisualGenerateResult>;
};

/**
 * Thrown when an AI provider cannot run (e.g. missing API key or not yet
 * implemented). The orchestrator treats this as a soft failure and falls back
 * to local_svg, so a misconfiguration never blocks generation or silently spends.
 */
export class VisualProviderNotEnabledError extends Error {
  readonly providerId: VisualProviderId;
  constructor(providerId: VisualProviderId, detail?: string) {
    super(`Visual provider "${providerId}" is not available${detail ? `: ${detail}` : "."}`);
    this.name = "VisualProviderNotEnabledError";
    this.providerId = providerId;
  }
}

export type PromptFields = {
  title: string;
  oneLiner: string;
  category: string;
  /** この作品固有の"作業画面"を描かせるためのUIコンテキスト（任意）。 */
  screenshotDescription?: string;
  coreInteraction?: string;
  primaryAction?: string;
  stateChange?: string;
  inspectableOutput?: string;
};

const clip = (value: string, max: number) =>
  value.length > max ? `${value.slice(0, max - 1).trimEnd()}…` : value;

/**
 * Product Hunt style showcase prompt (DOC-105 §"Product Showcase Prompt Template").
 * その作品の実UI（screenshotDescription/coreInteraction/primaryAction/stateChange）から
 * 具体的な"主要作業画面"を描かせる。汎用ダッシュボードや無関係なチャート、余白過多を避ける。
 * 文字はタイトルも含め一切描かせない（Imagenの既知弱点＝文字化け）。タイトル/カテゴリ/
 * ワンライナーは compose-thumbnail.ts が生成後に正確なテキストとして合成する。
 */
export const buildShowcasePrompt = (fields: PromptFields): string => {
  const workflow = [
    fields.screenshotDescription && `Main screen: ${clip(fields.screenshotDescription, 320)}`,
    fields.coreInteraction && `Core action the user performs: ${clip(fields.coreInteraction, 200)}`,
    fields.primaryAction && `Primary control/button on screen: ${clip(fields.primaryAction, 80)}`,
    fields.stateChange && `What visibly changes / the result shown: ${clip(fields.stateChange, 200)}`,
    fields.inspectableOutput && `Output the user inspects: ${clip(fields.inspectableOutput, 160)}`,
  ]
    .filter(Boolean)
    .join("\n");

  return `Create a polished Product Hunt gallery image: a realistic screenshot of THIS product's actual main work screen.

Style:
modern SaaS product screenshot, clean light background, soft blue gradient, one rounded desktop browser window,
realistic application UI in active use, subtle shadows, premium startup aesthetic — not a wireframe, not an icon collage.

Product (for context only — do NOT print the description in the image):
Name: ${clip(fields.title, 80)}
What it does: ${clip(fields.oneLiner, 160)}
Category: ${clip(fields.category, 60)}
${workflow ? `\nDepict THIS product's real main working screen (NOT a generic dashboard):\n${workflow}\n` : ""}
Composition:
16:9 landscape. A desktop browser window that FILLS most of the frame with minimal empty margins.
Lay out the concrete UI regions implied above — for example an input / drag-and-drop area, the primary control, and a result / output panel — as recognizable product UI arranged like a real app mid-task.
Show the product's actual controls (upload/drop zones, editors, media or waveform, before/after panels, lists, toggles). Only include a chart if the product is genuinely about metrics; otherwise do NOT draw charts.
Leave the top-left corner visually clear (no logo, no wordmark, no placeholder bar) — the product name is composited there afterward, not drawn by you.

CRITICAL — text handling:
Represent EVERY piece of interface text, including any heading or title, as plain solid light-gray rounded placeholder bars/blocks of varying widths (skeleton-loading UI style).
Do NOT write any words, letters, numbers, labels, or paragraphs anywhere in the image — not even the product name.

Avoid:
any readable words at all; gibberish or fake text; lorem ipsum; emoji; cartoon icons;
flat wireframe; hand-drawn style; excessive empty whitespace; unrelated generic charts.`;
};

/**
 * Open-Launch style icon prompt (DOC-105 §"Product Icon Prompt Template").
 * One abstract mark, 1-2 colors, no text.
 */
export const buildIconPrompt = (fields: PromptFields): string =>
  `Create a simple modern app icon for a SaaS product.

Style:
minimal vector logo, rounded square app icon, clean startup aesthetic,
bold simple symbol, high contrast, no text, no emoji, no mascot,
similar to modern Product Hunt / Open-Launch app icons.

Product:
Name: ${clip(fields.title, 80)}
Category: ${clip(fields.category, 60)}
Description: ${clip(fields.oneLiner, 160)}

Icon concept:
Represent the product's main function with one simple abstract mark.
Use 1-2 colors maximum.
Make it recognizable at 48x48 pixels.
Avoid complex illustration, screenshots, gradients with too many colors,
realistic objects, and cartoon style.`;

export const buildPromptForKind = (kind: ProductVisualKind, fields: PromptFields): string =>
  kind === "product_showcase" ? buildShowcasePrompt(fields) : buildIconPrompt(fields);
