export type MissionMode = "beginner" | "builder" | "deep-dive";

export type RepoFile = {
  id: string;
  path: string;
  role: "entry" | "component" | "config" | "data" | "test" | "docs" | "other";
  summary: string;
  referenceUrl: string | null;
};

export type MissionStep = {
  id: string;
  order: number;
  title: string;
  purpose: string;
  whyNow: string;
  estimatedMinutes: number;
  difficulty: "easy" | "medium" | "hard";
  repoFileIds: string[];
  actionType: "read" | "copy" | "run" | "modify" | "inspect";
  task: string;
  completionClue: string;
  stumblingPoint: string;
  recoveryHint: string;
};

export type RemixMission = {
  id: string;
  title: string;
  goal: string;
  targetFiles: string[];
  estimatedMinutes: number;
  successCheck: string;
  stretchIdea: string;
};

export type MissionQuality = {
  repoGroundingScore: number;
  actionabilityScore: number;
  remixPotentialScore: number;
  warnings: string[];
};

export type RepoMissionPlan = {
  id: string;
  repoMaterialId: string;
  mode: MissionMode;
  title: string;
  missionSummary: string;
  steps: MissionStep[];
  remixMission: RemixMission;
  quality: MissionQuality;
};

export type RepoMaterial = {
  id: string;
  sourceType: "github" | "repo_memo" | "sample_repo";
  title: string;
  url: string | null;
  stack: string[];
  repoSummary: string;
  detectedTopics: string[];
  entryPoints: string[];
  fileMap: RepoFile[];
  plans: Record<MissionMode, RepoMissionPlan>;
};

const commonQuality = {
  actionabilityScore: 92,
  repoGroundingScore: 88,
  warnings: ["Sample repo data only", "No live GitHub API access"],
};

export const repoMaterials: RepoMaterial[] = [
  {
    id: "agent-lab",
    sourceType: "sample_repo",
    title: "Agent Lab Starter",
    url: "https://github.com/example/agent-lab-starter",
    stack: ["TypeScript", "Node", "LLM tools", "Vitest"],
    repoSummary: "A small agent workflow repo with planner, tool runner, evaluator, and trace output.",
    detectedTopics: ["agent workflow", "tool calls", "eval trace", "prompt contracts"],
    entryPoints: ["src/agent/run-agent.ts", "src/agent/tools.ts", "src/eval/check-run.ts"],
    fileMap: [
      {
        id: "agent-entry",
        path: "src/agent/run-agent.ts",
        role: "entry",
        summary: "Starts the planner, runs tool calls, and emits a trace.",
        referenceUrl: null,
      },
      {
        id: "agent-tools",
        path: "src/agent/tools.ts",
        role: "component",
        summary: "Defines the small tool registry the agent can call.",
        referenceUrl: null,
      },
      {
        id: "agent-eval",
        path: "src/eval/check-run.ts",
        role: "test",
        summary: "Scores whether the agent followed the task contract.",
        referenceUrl: null,
      },
      {
        id: "agent-prompt",
        path: "prompts/planner.md",
        role: "docs",
        summary: "Planner prompt with required output fields and safety notes.",
        referenceUrl: null,
      },
    ],
    plans: {
      beginner: {
        id: "agent-lab-beginner",
        repoMaterialId: "agent-lab",
        mode: "beginner",
        title: "Trace first, tools second",
        missionSummary: "Follow one agent run from prompt to trace before modifying behavior.",
        steps: [
          {
            id: "agent-b-1",
            order: 1,
            title: "Find the run entry",
            purpose: "Understand where the agent starts.",
            whyNow: "The entry file shows the repo's main flow before details distract you.",
            estimatedMinutes: 6,
            difficulty: "easy",
            repoFileIds: ["agent-entry"],
            actionType: "read",
            task: "Read the function names and write down the three phases you see.",
            completionClue: "You can point to planner, tool execution, and trace emission.",
            stumblingPoint: "Trying to understand every imported helper at once.",
            recoveryHint: "Only follow top-level calls on the first pass.",
          },
          {
            id: "agent-b-2",
            order: 2,
            title: "Inspect the allowed tools",
            purpose: "See what the agent can actually do.",
            whyNow: "Agent behavior is bounded by the tool registry.",
            estimatedMinutes: 8,
            difficulty: "easy",
            repoFileIds: ["agent-tools"],
            actionType: "inspect",
            task: "List each tool name and the input it expects.",
            completionClue: "You have a small table of tool name, input, and output.",
            stumblingPoint: "Confusing tool descriptions with real external services.",
            recoveryHint: "Remember this sample does not call live services.",
          },
          {
            id: "agent-b-3",
            order: 3,
            title: "Run the evaluator mentally",
            purpose: "Connect trace output to quality checks.",
            whyNow: "The evaluator explains what this repo considers a successful agent run.",
            estimatedMinutes: 10,
            difficulty: "medium",
            repoFileIds: ["agent-eval"],
            actionType: "read",
            task: "Mark the checks that look strict and the checks that look heuristic.",
            completionClue: "You can explain why a trace passes or fails.",
            stumblingPoint: "Treating eval scores as objective truth.",
            recoveryHint: "Look for thresholds and comments; they reveal assumptions.",
          },
        ],
        remixMission: {
          id: "agent-remix-beginner",
          title: "Add a harmless dry-run tool",
          goal: "Add a fake summarize_files tool to the registry and mention it in the planner prompt.",
          targetFiles: ["src/agent/tools.ts", "prompts/planner.md"],
          estimatedMinutes: 30,
          successCheck: "The tool appears in the registry and the planner can choose it in a sample trace.",
          stretchIdea: "Add an eval check that rewards using the new tool only when file input exists.",
        },
        quality: {
          ...commonQuality,
          remixPotentialScore: 86,
        },
      },
      builder: {
        id: "agent-lab-builder",
        repoMaterialId: "agent-lab",
        mode: "builder",
        title: "Modify one loop safely",
        missionSummary: "Change the agent's behavior with one new tool and one eval guard.",
        steps: [
          {
            id: "agent-build-1",
            order: 1,
            title: "Map the control loop",
            purpose: "Identify the smallest safe edit point.",
            whyNow: "Builders need the loop boundary before changing tools.",
            estimatedMinutes: 8,
            difficulty: "medium",
            repoFileIds: ["agent-entry"],
            actionType: "inspect",
            task: "Draw the loop from plan to tool call to eval.",
            completionClue: "You know where to insert one guard without rewriting the repo.",
            stumblingPoint: "Editing the planner before seeing the trace contract.",
            recoveryHint: "Start from the emitted trace fields.",
          },
          {
            id: "agent-build-2",
            order: 2,
            title: "Add a tool contract",
            purpose: "Make the new capability explicit.",
            whyNow: "Tool interfaces are safer than free-form prompt changes.",
            estimatedMinutes: 12,
            difficulty: "medium",
            repoFileIds: ["agent-tools"],
            actionType: "modify",
            task: "Draft a summarize_files tool with typed input and sample output.",
            completionClue: "The tool has a name, input fields, and deterministic sample response.",
            stumblingPoint: "Adding network calls or filesystem reads too early.",
            recoveryHint: "Keep the first version static and inspectable.",
          },
          {
            id: "agent-build-3",
            order: 3,
            title: "Protect it with one eval",
            purpose: "Make the change testable.",
            whyNow: "A tool without an eval can silently make the workflow worse.",
            estimatedMinutes: 10,
            difficulty: "medium",
            repoFileIds: ["agent-eval"],
            actionType: "modify",
            task: "Add a check that the tool is used only when the task includes file context.",
            completionClue: "One failing and one passing trace are easy to imagine.",
            stumblingPoint: "Overbuilding a full test matrix.",
            recoveryHint: "Write one narrow check for this mission.",
          },
        ],
        remixMission: {
          id: "agent-remix-builder",
          title: "Give the agent one new sense",
          goal: "Add a fake file-summary sense and protect it with a narrow eval rule.",
          targetFiles: ["src/agent/tools.ts", "src/eval/check-run.ts"],
          estimatedMinutes: 30,
          successCheck: "The new tool is listed, used in the right situation, and caught by one eval.",
          stretchIdea: "Display the new tool result in the trace UI.",
        },
        quality: {
          ...commonQuality,
          repoGroundingScore: 91,
          remixPotentialScore: 94,
        },
      },
      "deep-dive": {
        id: "agent-lab-deep",
        repoMaterialId: "agent-lab",
        mode: "deep-dive",
        title: "Trace quality as architecture",
        missionSummary: "Treat the trace as the product surface and inspect how each file protects it.",
        steps: [
          {
            id: "agent-d-1",
            order: 1,
            title: "Read the prompt contract",
            purpose: "Find the schema the whole repo depends on.",
            whyNow: "Deep understanding starts with the contract between model and code.",
            estimatedMinutes: 8,
            difficulty: "medium",
            repoFileIds: ["agent-prompt"],
            actionType: "read",
            task: "Underline the fields the code must trust.",
            completionClue: "You can name which fields would break downstream parsing.",
            stumblingPoint: "Reading prompt prose without checking output fields.",
            recoveryHint: "Search only for required keys and safety constraints.",
          },
          {
            id: "agent-d-2",
            order: 2,
            title: "Follow schema assumptions",
            purpose: "See how prompt output becomes runtime behavior.",
            whyNow: "This reveals the hidden coupling between prompt and TypeScript.",
            estimatedMinutes: 12,
            difficulty: "hard",
            repoFileIds: ["agent-entry", "agent-tools"],
            actionType: "inspect",
            task: "Trace one required field from prompt to tool call.",
            completionClue: "You can explain one prompt-code dependency.",
            stumblingPoint: "Getting lost in all fields.",
            recoveryHint: "Pick exactly one field.",
          },
          {
            id: "agent-d-3",
            order: 3,
            title: "Stress the evaluator",
            purpose: "Find what the eval cannot see.",
            whyNow: "A good agent repo is defined by its blind spots.",
            estimatedMinutes: 10,
            difficulty: "hard",
            repoFileIds: ["agent-eval"],
            actionType: "inspect",
            task: "Write one bad trace that would still pass.",
            completionClue: "You found a concrete eval gap.",
            stumblingPoint: "Assuming the eval is a full judge.",
            recoveryHint: "Look for checks that count fields instead of judging usefulness.",
          },
        ],
        remixMission: {
          id: "agent-remix-deep",
          title: "Patch one eval blind spot",
          goal: "Add one quality check that catches a bad trace the current evaluator misses.",
          targetFiles: ["src/eval/check-run.ts", "prompts/planner.md"],
          estimatedMinutes: 30,
          successCheck: "The new check is narrow, explainable, and linked to one prompt requirement.",
          stretchIdea: "Add a trace fixture that demonstrates the blind spot.",
        },
        quality: {
          ...commonQuality,
          actionabilityScore: 87,
          repoGroundingScore: 94,
          remixPotentialScore: 91,
        },
      },
    },
  },
  {
    id: "next-commerce",
    sourceType: "sample_repo",
    title: "Tiny Next Commerce",
    url: "https://github.com/example/tiny-next-commerce",
    stack: ["Next.js", "React", "CSS Modules", "Static data"],
    repoSummary: "A small storefront with product data, category pages, cart state, and reusable cards.",
    detectedTopics: ["app router", "state", "product cards", "routing"],
    entryPoints: ["src/app/page.tsx", "src/products/catalog.ts", "src/cart/use-cart.ts"],
    fileMap: [
      {
        id: "shop-page",
        path: "src/app/page.tsx",
        role: "entry",
        summary: "Renders category navigation and product grid.",
        referenceUrl: null,
      },
      {
        id: "shop-card",
        path: "src/components/ProductCard.tsx",
        role: "component",
        summary: "Displays product summary and add-to-cart action.",
        referenceUrl: null,
      },
      {
        id: "shop-data",
        path: "src/products/catalog.ts",
        role: "data",
        summary: "Static product list with category and price fields.",
        referenceUrl: null,
      },
      {
        id: "shop-cart",
        path: "src/cart/use-cart.ts",
        role: "component",
        summary: "Client-side cart state and total calculation.",
        referenceUrl: null,
      },
    ],
    plans: {
      beginner: {
        id: "commerce-beginner",
        repoMaterialId: "next-commerce",
        mode: "beginner",
        title: "Product card first",
        missionSummary: "Understand the storefront by following one product from data to card to cart.",
        steps: [
          {
            id: "commerce-b-1",
            order: 1,
            title: "Start with one product",
            purpose: "Avoid getting lost in routes.",
            whyNow: "Static data is the easiest anchor.",
            estimatedMinutes: 5,
            difficulty: "easy",
            repoFileIds: ["shop-data"],
            actionType: "read",
            task: "Pick one product and list its fields.",
            completionClue: "You know which fields appear on screen.",
            stumblingPoint: "Opening every page before understanding the data.",
            recoveryHint: "Follow one item only.",
          },
          {
            id: "commerce-b-2",
            order: 2,
            title: "Find where fields render",
            purpose: "Connect data to UI.",
            whyNow: "The card shows the core component pattern.",
            estimatedMinutes: 8,
            difficulty: "easy",
            repoFileIds: ["shop-card"],
            actionType: "inspect",
            task: "Match each visible field to a prop or data field.",
            completionClue: "Every card label has a source field.",
            stumblingPoint: "Treating styling as logic.",
            recoveryHint: "Ignore CSS until fields are mapped.",
          },
          {
            id: "commerce-b-3",
            order: 3,
            title: "Trace one cart click",
            purpose: "See the first interactive state.",
            whyNow: "Cart state is the smallest behavior in the repo.",
            estimatedMinutes: 10,
            difficulty: "medium",
            repoFileIds: ["shop-cart", "shop-card"],
            actionType: "inspect",
            task: "Follow add-to-cart from button to total.",
            completionClue: "You can explain how a click changes total.",
            stumblingPoint: "Reading the whole hook before finding the click path.",
            recoveryHint: "Search for the add function name.",
          },
        ],
        remixMission: {
          id: "commerce-remix-beginner",
          title: "Add a 'best for' badge",
          goal: "Add one product field and show it as a badge on ProductCard.",
          targetFiles: ["src/products/catalog.ts", "src/components/ProductCard.tsx"],
          estimatedMinutes: 30,
          successCheck: "Each product can display a short best-for label.",
          stretchIdea: "Filter by the new badge.",
        },
        quality: {
          ...commonQuality,
          remixPotentialScore: 90,
        },
      },
      builder: {
        id: "commerce-builder",
        repoMaterialId: "next-commerce",
        mode: "builder",
        title: "Turn data into behavior",
        missionSummary: "Add one useful storefront behavior while touching only data, card, and cart.",
        steps: [
          {
            id: "commerce-build-1",
            order: 1,
            title: "Choose a product signal",
            purpose: "Pick one small feature axis.",
            whyNow: "A good modification starts with data shape.",
            estimatedMinutes: 6,
            difficulty: "easy",
            repoFileIds: ["shop-data"],
            actionType: "modify",
            task: "Add an isTrialFriendly boolean to two products.",
            completionClue: "The catalog compiles with the new field.",
            stumblingPoint: "Adding a feature without data.",
            recoveryHint: "Change the catalog first.",
          },
          {
            id: "commerce-build-2",
            order: 2,
            title: "Surface the signal",
            purpose: "Make the new data visible.",
            whyNow: "A modification should show a clear UI change.",
            estimatedMinutes: 10,
            difficulty: "medium",
            repoFileIds: ["shop-card"],
            actionType: "modify",
            task: "Show a Trial friendly badge when the flag is true.",
            completionClue: "Only marked products show the badge.",
            stumblingPoint: "Changing layout too much.",
            recoveryHint: "Add one small badge near the title.",
          },
          {
            id: "commerce-build-3",
            order: 3,
            title: "Use it in cart copy",
            purpose: "Connect visual signal to behavior.",
            whyNow: "The cart makes the change feel product-like.",
            estimatedMinutes: 12,
            difficulty: "medium",
            repoFileIds: ["shop-cart"],
            actionType: "modify",
            task: "Add a small cart note when any trial-friendly product is selected.",
            completionClue: "Cart state affects a user-facing message.",
            stumblingPoint: "Rewriting cart logic.",
            recoveryHint: "Derive the note from existing items.",
          },
        ],
        remixMission: {
          id: "commerce-remix-builder",
          title: "Make the shop recommendable",
          goal: "Add one field and one badge that explain who a product is best for.",
          targetFiles: ["src/products/catalog.ts", "src/components/ProductCard.tsx", "src/cart/use-cart.ts"],
          estimatedMinutes: 30,
          successCheck: "A product's fit is visible in both card and cart.",
          stretchIdea: "Add a one-click filter for trial-friendly products.",
        },
        quality: {
          ...commonQuality,
          actionabilityScore: 94,
          remixPotentialScore: 93,
        },
      },
      "deep-dive": {
        id: "commerce-deep",
        repoMaterialId: "next-commerce",
        mode: "deep-dive",
        title: "State boundary inspection",
        missionSummary: "Understand where server-rendered data stops and client state begins.",
        steps: [
          {
            id: "commerce-d-1",
            order: 1,
            title: "Mark server data",
            purpose: "Separate static rendering from interaction.",
            whyNow: "Next.js repos become easier when boundaries are explicit.",
            estimatedMinutes: 8,
            difficulty: "medium",
            repoFileIds: ["shop-page", "shop-data"],
            actionType: "inspect",
            task: "List which values can render without client state.",
            completionClue: "You can separate catalog fields from cart fields.",
            stumblingPoint: "Treating every component as client-side.",
            recoveryHint: "Look for the cart hook boundary.",
          },
          {
            id: "commerce-d-2",
            order: 2,
            title: "Follow client state",
            purpose: "Find the minimum stateful surface.",
            whyNow: "This shows where interaction lives.",
            estimatedMinutes: 12,
            difficulty: "hard",
            repoFileIds: ["shop-cart", "shop-card"],
            actionType: "inspect",
            task: "Trace state from button click to displayed total.",
            completionClue: "You can name the state owner and consumers.",
            stumblingPoint: "Confusing props and derived state.",
            recoveryHint: "Write down what changes after the click.",
          },
          {
            id: "commerce-d-3",
            order: 3,
            title: "Design one boundary-safe feature",
            purpose: "Make a change without blurring server/client roles.",
            whyNow: "Good app-router changes respect boundaries.",
            estimatedMinutes: 10,
            difficulty: "hard",
            repoFileIds: ["shop-page", "shop-card", "shop-cart"],
            actionType: "modify",
            task: "Plan a feature with one static field and one client response.",
            completionClue: "You know which file owns each part.",
            stumblingPoint: "Putting all logic in one component.",
            recoveryHint: "Keep static facts in catalog and actions in cart.",
          },
        ],
        remixMission: {
          id: "commerce-remix-deep",
          title: "Add a boundary-safe recommendation",
          goal: "Use static catalog fields to drive a client-side cart recommendation.",
          targetFiles: ["src/products/catalog.ts", "src/cart/use-cart.ts"],
          estimatedMinutes: 30,
          successCheck: "Static product facts and client state remain clearly separated.",
          stretchIdea: "Add a small test for cart recommendation text.",
        },
        quality: {
          ...commonQuality,
          repoGroundingScore: 93,
          remixPotentialScore: 88,
        },
      },
    },
  },
  {
    id: "ui-kit",
    sourceType: "sample_repo",
    title: "Focus UI Kit",
    url: "https://github.com/example/focus-ui-kit",
    stack: ["React", "Storybook", "CSS variables", "Testing Library"],
    repoSummary: "A compact component kit with Button, Tabs, Toast, and form field examples.",
    detectedTopics: ["component API", "design tokens", "states", "accessibility"],
    entryPoints: ["src/components/Button.tsx", "src/styles/tokens.css", "stories/Button.stories.tsx"],
    fileMap: [
      {
        id: "ui-button",
        path: "src/components/Button.tsx",
        role: "component",
        summary: "Core button component with variants and disabled state.",
        referenceUrl: null,
      },
      {
        id: "ui-tabs",
        path: "src/components/Tabs.tsx",
        role: "component",
        summary: "Segmented tab component with keyboard-focused state.",
        referenceUrl: null,
      },
      {
        id: "ui-tokens",
        path: "src/styles/tokens.css",
        role: "config",
        summary: "Color, spacing, and border tokens shared by components.",
        referenceUrl: null,
      },
      {
        id: "ui-story",
        path: "stories/Button.stories.tsx",
        role: "docs",
        summary: "Storybook examples for component states.",
        referenceUrl: null,
      },
    ],
    plans: {
      beginner: {
        id: "ui-beginner",
        repoMaterialId: "ui-kit",
        mode: "beginner",
        title: "Button as the map",
        missionSummary: "Use one component to understand variants, tokens, and examples.",
        steps: [
          {
            id: "ui-b-1",
            order: 1,
            title: "Read the component API",
            purpose: "Learn how the kit exposes behavior.",
            whyNow: "Button is the smallest component with meaningful variants.",
            estimatedMinutes: 6,
            difficulty: "easy",
            repoFileIds: ["ui-button"],
            actionType: "read",
            task: "List the props and states Button accepts.",
            completionClue: "You know how to render primary, quiet, and disabled states.",
            stumblingPoint: "Starting with visual tokens before API.",
            recoveryHint: "Read props first, styles second.",
          },
          {
            id: "ui-b-2",
            order: 2,
            title: "Find the token source",
            purpose: "Connect component appearance to shared design rules.",
            whyNow: "Tokens explain why variants look consistent.",
            estimatedMinutes: 8,
            difficulty: "easy",
            repoFileIds: ["ui-tokens"],
            actionType: "inspect",
            task: "Find color and spacing tokens used by Button.",
            completionClue: "You can point to at least two token names.",
            stumblingPoint: "Hard-coding colors in the component.",
            recoveryHint: "Search for var(--...) usage.",
          },
          {
            id: "ui-b-3",
            order: 3,
            title: "Check the stories",
            purpose: "See intended states in one place.",
            whyNow: "Stories are the fastest way to learn expected usage.",
            estimatedMinutes: 8,
            difficulty: "medium",
            repoFileIds: ["ui-story"],
            actionType: "read",
            task: "Match each story to a Button prop combination.",
            completionClue: "You can add one new story without guessing.",
            stumblingPoint: "Treating stories as tests.",
            recoveryHint: "Use them as examples first.",
          },
        ],
        remixMission: {
          id: "ui-remix-beginner",
          title: "Add a loading state",
          goal: "Add a loading prop to Button and one story showing it.",
          targetFiles: ["src/components/Button.tsx", "stories/Button.stories.tsx"],
          estimatedMinutes: 30,
          successCheck: "Loading state disables action and shows stable text or spinner.",
          stretchIdea: "Add a reduced-motion variant.",
        },
        quality: {
          ...commonQuality,
          remixPotentialScore: 92,
        },
      },
      builder: {
        id: "ui-builder",
        repoMaterialId: "ui-kit",
        mode: "builder",
        title: "State-driven component change",
        missionSummary: "Add one state to a component and propagate it through token and story surfaces.",
        steps: [
          {
            id: "ui-build-1",
            order: 1,
            title: "Choose the state",
            purpose: "Make the modification narrow.",
            whyNow: "Component kits reward small consistent changes.",
            estimatedMinutes: 5,
            difficulty: "easy",
            repoFileIds: ["ui-button"],
            actionType: "modify",
            task: "Add a loading prop to the Button type.",
            completionClue: "The prop is typed and defaults to false.",
            stumblingPoint: "Adding multiple visual ideas at once.",
            recoveryHint: "Only add loading.",
          },
          {
            id: "ui-build-2",
            order: 2,
            title: "Make style token-safe",
            purpose: "Keep design system consistency.",
            whyNow: "New states should reuse shared tokens.",
            estimatedMinutes: 10,
            difficulty: "medium",
            repoFileIds: ["ui-tokens", "ui-button"],
            actionType: "modify",
            task: "Style loading with existing muted/disabled tokens.",
            completionClue: "No new raw hex colors are needed.",
            stumblingPoint: "Inventing one-off styles.",
            recoveryHint: "Reuse disabled styles first.",
          },
          {
            id: "ui-build-3",
            order: 3,
            title: "Prove it in stories",
            purpose: "Make the state inspectable.",
            whyNow: "Stories are the public contract of this repo.",
            estimatedMinutes: 12,
            difficulty: "medium",
            repoFileIds: ["ui-story"],
            actionType: "modify",
            task: "Add one Loading story and one Disabled comparison.",
            completionClue: "A reviewer can inspect both states side by side.",
            stumblingPoint: "Only testing with one variant.",
            recoveryHint: "Show primary loading and quiet disabled.",
          },
        ],
        remixMission: {
          id: "ui-remix-builder",
          title: "Ship one new state cleanly",
          goal: "Add loading to Button with token-safe styling and a story example.",
          targetFiles: ["src/components/Button.tsx", "src/styles/tokens.css", "stories/Button.stories.tsx"],
          estimatedMinutes: 30,
          successCheck: "The new state is typed, visually stable, and documented in stories.",
          stretchIdea: "Add an accessibility note for busy state.",
        },
        quality: {
          ...commonQuality,
          actionabilityScore: 95,
          remixPotentialScore: 90,
        },
      },
      "deep-dive": {
        id: "ui-deep",
        repoMaterialId: "ui-kit",
        mode: "deep-dive",
        title: "API consistency audit",
        missionSummary: "Compare Button and Tabs to understand the kit's design rules.",
        steps: [
          {
            id: "ui-d-1",
            order: 1,
            title: "Compare prop shapes",
            purpose: "Find consistency rules.",
            whyNow: "Deep component work starts with API patterns.",
            estimatedMinutes: 8,
            difficulty: "medium",
            repoFileIds: ["ui-button", "ui-tabs"],
            actionType: "inspect",
            task: "Write down where Button and Tabs use similar naming.",
            completionClue: "You can identify one consistent and one inconsistent prop pattern.",
            stumblingPoint: "Only comparing visuals.",
            recoveryHint: "Compare prop names and state names.",
          },
          {
            id: "ui-d-2",
            order: 2,
            title: "Trace token dependencies",
            purpose: "Understand visual system coupling.",
            whyNow: "Token choices reveal the design contract.",
            estimatedMinutes: 10,
            difficulty: "hard",
            repoFileIds: ["ui-tokens", "ui-button", "ui-tabs"],
            actionType: "inspect",
            task: "Find shared tokens used by both components.",
            completionClue: "You know which tokens must remain stable.",
            stumblingPoint: "Changing tokens without seeing all consumers.",
            recoveryHint: "Search token names across components.",
          },
          {
            id: "ui-d-3",
            order: 3,
            title: "Plan one breaking-change-free fix",
            purpose: "Improve consistency safely.",
            whyNow: "A design kit modification should protect existing users.",
            estimatedMinutes: 12,
            difficulty: "hard",
            repoFileIds: ["ui-button", "ui-tabs", "ui-story"],
            actionType: "modify",
            task: "Draft a non-breaking alias or story note for one inconsistent prop.",
            completionClue: "Existing stories still make sense.",
            stumblingPoint: "Renaming props directly.",
            recoveryHint: "Add compatibility before removal.",
          },
        ],
        remixMission: {
          id: "ui-remix-deep",
          title: "Make one API safer",
          goal: "Add a non-breaking API improvement and document it in stories.",
          targetFiles: ["src/components/Button.tsx", "src/components/Tabs.tsx", "stories/Button.stories.tsx"],
          estimatedMinutes: 30,
          successCheck: "The old usage still works and the new clearer usage is documented.",
          stretchIdea: "Add a migration note component.",
        },
        quality: {
          ...commonQuality,
          repoGroundingScore: 90,
          remixPotentialScore: 84,
        },
      },
    },
  },
];
